name: papi_burgers
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  google_maps_flutter: ^2.5.3
  mask_text_input_formatter: ^2.8.0
  animated_snack_bar: ^0.4.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  pin_code_fields: ^8.0.1
  auto_route: ^7.8.4
  provider: ^6.1.1
  cloud_firestore: ^4.15.3
  sqflite: ^2.3.2
  grouped_list: ^5.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/
