final List<Map<String, dynamic>> extraIngredientsList = [
  {"name": "Айсберг", "price": 40},
  {"name": "Фалафель", "price": 90},
  {"name": "Жаренный лук", "price": 50},
  {"name": "Кетчуп", "price": 90},
  {"name": "Куриное филе в панировке", "price": 90},
  {"name": "Котлета", "price": 220},
  {"name": "Яйцо куриное", "price": 60},
  {"name": "Креветки", "price": 190},
  {"name": "Лук красный", "price": 20},
  {"name": "Огурец", "price": 60},
  {"name": "Огурец маринованный", "price": 60},
  {"name": "Томаты", "price": 90},
  {"name": "Халапеньо", "price": 60},
  {"name": "Пармезан", "price": 80},
  {"name": "Сыр Чеддер", "price": 90},
  {"name": "Сыр Сулугуни", "price": 90},
  {"name": "Сыр Моцарелла", "price": 90},
  {"name": "Соус горчичный", "price": 90},
  {"name": "Соус BBQ", "price": 90},
  {"name": "Соус Брусничный", "price": 90},
  {"name": "Соус Гриль", "price": 90},
  {"name": "Соус Руй", "price": 90},
  {"name": "Соус Сальса", "price": 90},
  {"name": "Соус Сладкий Чили", "price": 90},
  {"name": "Соус Сырный", "price": 90},
  {"name": "Соус Терияки", "price": 90},
  {"name": "Соус Трюфельный", "price": 90},
  {"name": "Соус Шрирача", "price": 90},
  {"name": "Соус Сацебели", "price": 90},
];
